name: "05 Â· Combinaison + schedule"
 
on:
  push:
    branches:
      - main
      - develop
 
  pull_request:
    branches:
      - main
 
  schedule:
    - cron: "23 16 * * 5"   
 
  workflow_dispatch:       
 
jobs:
  rapport:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“Š Identifier l'origine du dÃ©clenchement
        run: |
          echo " Workflow lancÃ© !"
          echo " Ã‰vÃ©nement    : ${{ github.event_name }}"
          echo " Acteur       : ${{ github.actor }}"
          echo "ðŸŒ¿ Branche      : ${{ github.ref_name }}"
          echo "ðŸ”¢ Run nÂ°       : ${{ github.run_number }}"
 